sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t sagarpalnitkar/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true sagarpalnitkar/react-test npm test -- --coverage

after_success:
    - docker build -t sagarpalnitkar/multi-client ./client
    - docker build -t sagarpalnitkar/multi-nginx ./nginx
    - docker build -t sagarpalnitkar/multi-server ./server
    - docker build -t sagarpalnitkar/multi-worker ./worker
    #Login docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sagarpalnitkar/multi-client 
    - docker push sagarpalnitkar/multi-nginx 
    - docker push sagarpalnitkar/multi-server 
    - docker push sagarpalnitkar/multi-worker 


